### ISSUE TITLE
Update positive examples and data splitting

### ISSUE THREAD

**Issue by updbqn** [RI-SE/smirk#16]
Two additional pedestrian models have been added to the dataset:

- **Business casual female**
- **Casual male**

Previous **casual male** has been renamed to **business casual male**.

The new naming of positive examples is as follows:

- [P1] Casual female
- [P2] Casual male
- [P3] Business casual female
- [P4] Business casual male
- [P5] Business female
- [P6] Business male
- [P7] Child
- [P8] Male construction worker

The data split is updated to:

- Development [P2][P3][P6][N5] (see #15)
- Internal Test [P1][P4][N1][N2]
- Verification [P5][P7][P8][N3][N4]

**Comment by mrksbrg** [comment]
Cones and pyramids are very similar - let's not put them both in the verification data. The same goes for cubes and cylinders, although they already are in sequestered sets. 

We will use the following data split instead:
- Development [P2][P3][P6][N5]
- Internal Test [P1][P4][N1][N3]
- Verification [P5][P7][P8][N2][N4]

**Comment by mrksbrg** [comment]
For reference: 
![bild](https://user-images.githubusercontent.com/5861909/162559852-9a1e0bb5-77fd-4452-a8e3-9f47d4b15b8c.png)
