### ISSUE TITLE
Is there any a hint or clue for another simulator？

### ISSUE THREAD

**Issue by luakuc** [RI-SE/smirk#29]
May I use another open source simulator to build a research enviroment, like Carla?  if Yes, could you please provide what folder shoule be cared?

**Comment by updbqn** [comment]
Most parts are somewhat coupled to ESI Pro-SiVIC at the moment. Depending on what you want to do it might require quite a bit of effort to use Carla. There are plans to add support for Carla and possibly other simulators, but no set timeline. @mrksbrg might know more.

**Comment by mrksbrg** [comment]
Porting to CARLA has been a goal for a while. It remains on the backlog for current PhD students, but not a priority at the moment. We presented the work at [The Int'l. Requirements Engineering Conference](https://conf.researchr.org/home/RE-2023) two days ago. Of course we hope for an increased interest in the demonstrator and potential more helping hands.
